import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Header from "@/components/Header";
import Providers from "@/providers";
import BodyBackground from "@/utils/BodyBackground";
import { cn } from "@/utils/utils";

const robotoSans = Roboto({
  style: ["normal", "italic"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" data-theme="sky">
      <body
        className={cn(
          "bg-[var(--body-bg)] transition-colors duration-300",
          `${robotoSans.variable} antialiased`
        )}
      >
        <BodyBackground />
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
