import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Header from "@/components/Header";

const robotoSans = Roboto({
  style: ["normal", "italic"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" data-theme="rose">
      <body className={`${robotoSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
